# Generated by Django 3.2.3 on 2021-07-30 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserPanel', '0002_auto_20210730_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='att_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendence',
            name='att_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
