# Generated by Django 3.2.3 on 2021-08-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPanel', '0005_auto_20210731_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='req_status',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('N', 'Not Approved')], default='Pending', max_length=1),
        ),
    ]
