# Generated by Django 3.2.3 on 2021-08-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPanel', '0006_leaverequest_req_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_cnic',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
